sudo: required
services:
  - docker

before_install:

script:

after_success:
  - docker build -t feraykizilsu/multi-client ./client
  - docker build -t feraykizilsu/multi-nginx ./nginx
  - docker build -t feraykizilsu/multi-server ./server
  - docker build -t feraykizilsu/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push feraykizilsu/multi-client
  - docker push feraykizilsu/multi-nginx
  - docker push feraykizilsu/multi-server
  - docker push feraykizilsu/multi-worker

